import Header from "@/components/shared/header";

export const metadata = {
  title: "Ideal Mobile Detailing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen flex-col">
      <Header />
      <main className="flex-1 wrapper">
        {children}
      </main>
    </div>
  );
}
