import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header";
import Hero from "@/components/shared/hero/hero";

export const metadata = {
  title: "Ideal Mobile Detailing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <Hero />
      <main className="flex-1 wrapper">
        {children}
      </main>
      <Footer />
    </div>
  );
}
